SRC_SLIDES    = seminar_yw
PDF_SLIDES	= $(SRC_SLIDES).pdf
SRC_HANDOUT = seminar_yw_handout
PDF_HANDOUT = $(SRC_HANDOUT).pdf
SRC_NOTES = seminar_yw_notes
PDF_NOTES = $(SRC_NOTES).pdf
SRC_FULL = seminar_yw_full
PDF_FULL = $(SRC_FULL).pdf
STY_DIR = ../../../9_interview/0_slides_common
COMPILE = latexmk 
CACHE_DIR = .cache
RM = rm -rf
FIG_DIR = fig
FIG_CONVERT = inkscape --export-type=pdf --export-area-page --export-dpi=1200
PDF_COMPRESS = gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 -dPDFSETTINGS=/prepress -dColorImageResolution=600 -dNOPAUSE -dQUIET -dBATCH

FIG1_1_SVG = $(FIG_DIR)/bw_taper-1.svg
FIG1_1_PDF = $(FIG1_1_SVG:.svg=.pdf)
FIG1_2_SVG = $(FIG_DIR)/bw_taper-2.svg
FIG1_2_PDF = $(FIG1_2_SVG:.svg=.pdf)
FIG1_3_SVG = $(FIG_DIR)/bw_taper-3.svg
FIG1_3_PDF = $(FIG1_3_SVG:.svg=.pdf)
FIG1_4_SVG = $(FIG_DIR)/bw_taper-4.svg
FIG1_4_PDF = $(FIG1_4_SVG:.svg=.pdf)
FIG1_5_SVG = $(FIG_DIR)/bw_taper-5.svg
FIG1_5_PDF = $(FIG1_5_SVG:.svg=.pdf)
FIG2_1_SVG = $(FIG_DIR)/model_growth-1.svg
FIG2_1_PDF = $(FIG2_1_SVG:.svg=.pdf)
FIG2_2_SVG = $(FIG_DIR)/model_growth-2.svg
FIG2_2_PDF = $(FIG2_2_SVG:.svg=.pdf)
FIG2_3_SVG = $(FIG_DIR)/model_growth-3.svg
FIG2_3_PDF = $(FIG2_3_SVG:.svg=.pdf)
FIG3_1_SVG = $(FIG_DIR)/energy_growth-1.svg
FIG3_1_PDF = $(FIG3_1_SVG:.svg=.pdf)
FIG3_2_SVG = $(FIG_DIR)/energy_growth-2.svg
FIG3_2_PDF = $(FIG3_2_SVG:.svg=.pdf)
FIG3_3_SVG = $(FIG_DIR)/energy_growth-3.svg
FIG3_3_PDF = $(FIG3_3_SVG:.svg=.pdf)
FIG3_4_SVG = $(FIG_DIR)/energy_growth-4.svg
FIG3_4_PDF = $(FIG3_4_SVG:.svg=.pdf)
FIG4_1_SVG = $(FIG_DIR)/cpo-1.svg
FIG4_1_PDF = $(FIG4_1_SVG:.svg=.pdf)
FIG4_2_SVG = $(FIG_DIR)/cpo-2.svg
FIG4_2_PDF = $(FIG4_2_SVG:.svg=.pdf)
FIG5_1_SVG = $(FIG_DIR)/fom-1.svg
FIG5_1_PDF = $(FIG5_1_SVG:.svg=.pdf)
FIG5_2_SVG = $(FIG_DIR)/fom-2.svg
FIG5_2_PDF = $(FIG5_2_SVG:.svg=.pdf)
FIG5_3_SVG = $(FIG_DIR)/fom-3.svg
FIG5_3_PDF = $(FIG5_3_SVG:.svg=.pdf)
FIG5_4_SVG = $(FIG_DIR)/fom-4.svg
FIG5_4_PDF = $(FIG5_4_SVG:.svg=.pdf)
FIG6_1_SVG = $(FIG_DIR)/dwdm-1.svg
FIG6_1_PDF = $(FIG6_1_SVG:.svg=.pdf)
FIG6_2_SVG = $(FIG_DIR)/dwdm-2.svg
FIG6_2_PDF = $(FIG6_2_SVG:.svg=.pdf)
FIG6_3_SVG = $(FIG_DIR)/dwdm-3.svg
FIG6_3_PDF = $(FIG6_3_SVG:.svg=.pdf)
FIG6_4_SVG = $(FIG_DIR)/dwdm-4.svg
FIG6_4_PDF = $(FIG6_4_SVG:.svg=.pdf)
FIG7_1_SVG = $(FIG_DIR)/arch-1.svg
FIG7_1_PDF = $(FIG7_1_SVG:.svg=.pdf)
FIG7_2_SVG = $(FIG_DIR)/arch-2.svg
FIG7_2_PDF = $(FIG7_2_SVG:.svg=.pdf)
FIG7_3_SVG = $(FIG_DIR)/arch-3.svg
FIG7_3_PDF = $(FIG7_3_SVG:.svg=.pdf)
FIG7_4_SVG = $(FIG_DIR)/arch-4.svg
FIG7_4_PDF = $(FIG7_4_SVG:.svg=.pdf)
FIG7_5_SVG = $(FIG_DIR)/arch-5.svg
FIG7_5_PDF = $(FIG7_5_SVG:.svg=.pdf)
FIG7_6_SVG = $(FIG_DIR)/arch-6.svg
FIG7_6_PDF = $(FIG7_6_SVG:.svg=.pdf)
FIG7_7_SVG = $(FIG_DIR)/arch-7.svg
FIG7_7_PDF = $(FIG7_7_SVG:.svg=.pdf)
FIG7_8_SVG = $(FIG_DIR)/arch-8.svg
FIG7_8_PDF = $(FIG7_8_SVG:.svg=.pdf)
FIG7_9_SVG = $(FIG_DIR)/arch-9.svg
FIG7_9_PDF = $(FIG7_9_SVG:.svg=.pdf)
FIG8_1_SVG = $(FIG_DIR)/dispersion-1.svg
FIG8_1_PDF = $(FIG8_1_SVG:.svg=.pdf)
FIG8_2_SVG = $(FIG_DIR)/dispersion-2.svg
FIG8_2_PDF = $(FIG8_2_SVG:.svg=.pdf)
FIG9_1_SVG = $(FIG_DIR)/interleaver-1.svg
FIG9_1_PDF = $(FIG9_1_SVG:.svg=.pdf)
FIG9_2_SVG = $(FIG_DIR)/interleaver-2.svg
FIG9_2_PDF = $(FIG9_2_SVG:.svg=.pdf)
FIG10_SVG = $(FIG_DIR)/variation.svg
FIG10_PDF = $(FIG10_SVG:.svg=.pdf)
FIG11_1_SVG = $(FIG_DIR)/validation-1.svg
FIG11_1_PDF = $(FIG11_1_SVG:.svg=.pdf)
FIG11_2_SVG = $(FIG_DIR)/validation-2.svg
FIG11_2_PDF = $(FIG11_2_SVG:.svg=.pdf)
FIG11_3_SVG = $(FIG_DIR)/validation-3.svg
FIG11_3_PDF = $(FIG11_3_SVG:.svg=.pdf)
FIG11_4_SVG = $(FIG_DIR)/validation-4.svg
FIG11_4_PDF = $(FIG11_4_SVG:.svg=.pdf)
FIG12_1_SVG = $(FIG_DIR)/integration-1.svg
FIG12_1_PDF = $(FIG12_1_SVG:.svg=.pdf)
FIG12_2_SVG = $(FIG_DIR)/integration-2.svg
FIG12_2_PDF = $(FIG12_2_SVG:.svg=.pdf)
FIG13_1_SVG = $(FIG_DIR)/mcp-1.svg
FIG13_1_PDF = $(FIG13_1_SVG:.svg=.pdf)
FIG13_2_SVG = $(FIG_DIR)/mcp-2.svg
FIG13_2_PDF = $(FIG13_2_SVG:.svg=.pdf)
FIG14_1_SVG = $(FIG_DIR)/sipam-1.svg
FIG14_1_PDF = $(FIG14_1_SVG:.svg=.pdf)
FIG14_2_SVG = $(FIG_DIR)/sipam-2.svg
FIG14_2_PDF = $(FIG14_2_SVG:.svg=.pdf)
FIG14_3_SVG = $(FIG_DIR)/sipam-3.svg
FIG14_3_PDF = $(FIG14_3_SVG:.svg=.pdf)
FIG15_1_SVG = $(FIG_DIR)/assembly-1.svg
FIG15_1_PDF = $(FIG15_1_SVG:.svg=.pdf)
FIG15_2_SVG = $(FIG_DIR)/assembly-2.svg
FIG15_2_PDF = $(FIG15_2_SVG:.svg=.pdf)
FIG16_1_SVG = $(FIG_DIR)/pic-1.svg
FIG16_1_PDF = $(FIG16_1_SVG:.svg=.pdf)
FIG16_2_SVG = $(FIG_DIR)/pic-2.svg
FIG16_2_PDF = $(FIG16_2_SVG:.svg=.pdf)
FIG17_SVG = $(FIG_DIR)/flat-top.svg
FIG17_PDF = $(FIG17_SVG:.svg=.pdf)
FIG18_1_SVG = $(FIG_DIR)/int-tuning-1.svg
FIG18_1_PDF = $(FIG18_1_SVG:.svg=.pdf)
FIG18_2_SVG = $(FIG_DIR)/int-tuning-2.svg
FIG18_2_PDF = $(FIG18_2_SVG:.svg=.pdf)
FIG18_3_SVG = $(FIG_DIR)/int-tuning-3.svg
FIG18_3_PDF = $(FIG18_3_SVG:.svg=.pdf)
FIG19_SVG = $(FIG_DIR)/disk-ring.svg
FIG19_PDF = $(FIG19_SVG:.svg=.pdf)
FIG20_1_SVG = $(FIG_DIR)/robust-array-1.svg
FIG20_1_PDF = $(FIG20_1_SVG:.svg=.pdf)
FIG20_2_SVG = $(FIG_DIR)/robust-array-2.svg
FIG20_2_PDF = $(FIG20_2_SVG:.svg=.pdf)
FIG21_1_SVG = $(FIG_DIR)/dwdm-cali-1.svg
FIG21_1_PDF = $(FIG21_1_SVG:.svg=.pdf)
FIG21_2_SVG = $(FIG_DIR)/dwdm-cali-2.svg
FIG21_2_PDF = $(FIG21_2_SVG:.svg=.pdf)
FIG21_3_SVG = $(FIG_DIR)/dwdm-cali-3.svg
FIG21_3_PDF = $(FIG21_3_SVG:.svg=.pdf)

.PHONY: all clean clean-cache

all: slides figs

slides: $(PDF_SLIDES) $(PDF_HANDOUT) $(PDF_NOTES) $(PDF_FULL)

$(PDF_SLIDES): figs $(SRC_SLIDES).tex
	@cp $(STY_DIR)/*.sty .
	$(COMPILE) -lualatex -outdir=$(CACHE_DIR) --shell-escape $(SRC_SLIDES).tex
	@cp $(CACHE_DIR)/$(SRC_SLIDES).pdf .

$(PDF_HANDOUT): figs $(SRC_HANDOUT).tex
	@cp $(STY_DIR)/*.sty .
	$(COMPILE) -lualatex -outdir=$(CACHE_DIR) --shell-escape $(SRC_HANDOUT).tex
	@cp $(CACHE_DIR)/$(SRC_HANDOUT).pdf .

$(PDF_NOTES): figs $(SRC_NOTES).tex
	@cp $(STY_DIR)/*.sty .
	$(COMPILE) -lualatex -outdir=$(CACHE_DIR) --shell-escape $(SRC_NOTES).tex
	@cp $(CACHE_DIR)/$(SRC_NOTES).pdf .

$(PDF_FULL): figs $(SRC_FULL).tex
	@cp $(STY_DIR)/*.sty .
	$(COMPILE) -lualatex -outdir=$(CACHE_DIR) --shell-escape $(SRC_FULL).tex
	@cp $(CACHE_DIR)/$(SRC_FULL).pdf .

figs: $(FIG1_1_PDF) $(FIG1_2_PDF) $(FIG1_3_PDF) $(FIG1_4_PDF) $(FIG1_5_PDF) $(FIG2_1_PDF) $(FIG2_2_PDF) $(FIG2_3_PDF) $(FIG3_1_PDF) $(FIG3_2_PDF) $(FIG3_3_PDF) $(FIG3_4_PDF) $(FIG4_1_PDF) $(FIG4_2_PDF) $(FIG5_1_PDF) $(FIG5_2_PDF) $(FIG5_3_PDF) $(FIG5_4_PDF) $(FIG6_1_PDF) $(FIG6_2_PDF) $(FIG6_3_PDF) $(FIG6_4_PDF) $(FIG7_1_PDF) $(FIG7_2_PDF) $(FIG7_3_PDF) $(FIG7_4_PDF) $(FIG7_5_PDF) $(FIG7_6_PDF) $(FIG7_7_PDF) $(FIG7_8_PDF) $(FIG7_9_PDF) $(FIG8_1_PDF) $(FIG8_2_PDF) $(FIG9_1_PDF) $(FIG9_2_PDF) $(FIG10_PDF) $(FIG11_1_PDF) $(FIG11_2_PDF) $(FIG11_3_PDF) $(FIG11_4_PDF) $(FIG12_1_PDF) $(FIG12_2_PDF) $(FIG13_1_PDF) $(FIG13_2_PDF) $(FIG14_1_PDF) $(FIG14_2_PDF) $(FIG14_3_PDF) $(FIG15_1_PDF) $(FIG15_2_PDF) $(FIG16_1_PDF) $(FIG16_2_PDF) $(FIG17_PDF) $(FIG18_1_PDF) $(FIG18_2_PDF) $(FIG18_3_PDF) $(FIG19_PDF) $(FIG20_1_PDF) $(FIG20_2_PDF) $(FIG21_1_PDF) $(FIG21_2_PDF) $(FIG21_3_PDF)

$(FIG1_1_PDF): $(FIG1_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG1_1_PDF) $(FIG1_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG1_1_PDF))_compressed.pdf $(FIG1_1_PDF)

$(FIG1_2_PDF): $(FIG1_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG1_2_PDF) $(FIG1_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG1_2_PDF))_compressed.pdf $(FIG1_2_PDF)

$(FIG1_3_PDF): $(FIG1_3_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG1_3_PDF) $(FIG1_3_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG1_3_PDF))_compressed.pdf $(FIG1_3_PDF)

$(FIG1_4_PDF): $(FIG1_4_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG1_4_PDF) $(FIG1_4_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG1_4_PDF))_compressed.pdf $(FIG1_4_PDF)

$(FIG1_5_PDF): $(FIG1_5_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG1_5_PDF) $(FIG1_5_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG1_5_PDF))_compressed.pdf $(FIG1_5_PDF)

$(FIG2_1_PDF): $(FIG2_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG2_1_PDF) $(FIG2_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG2_1_PDF))_compressed.pdf $(FIG2_1_PDF)

$(FIG2_2_PDF): $(FIG2_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG2_2_PDF) $(FIG2_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG2_2_PDF))_compressed.pdf $(FIG2_2_PDF)

$(FIG2_3_PDF): $(FIG2_3_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG2_3_PDF) $(FIG2_3_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG2_3_PDF))_compressed.pdf $(FIG2_3_PDF)

$(FIG3_1_PDF): $(FIG3_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG3_1_PDF) $(FIG3_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG3_1_PDF))_compressed.pdf $(FIG3_1_PDF)

$(FIG3_2_PDF): $(FIG3_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG3_2_PDF) $(FIG3_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG3_2_PDF))_compressed.pdf $(FIG3_2_PDF)

$(FIG3_3_PDF): $(FIG3_3_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG3_3_PDF) $(FIG3_3_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG3_3_PDF))_compressed.pdf $(FIG3_3_PDF)

$(FIG3_4_PDF): $(FIG3_4_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG3_4_PDF) $(FIG3_4_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG3_4_PDF))_compressed.pdf $(FIG3_4_PDF)

$(FIG4_1_PDF): $(FIG4_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG4_1_PDF) $(FIG4_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG4_1_PDF))_compressed.pdf $(FIG4_1_PDF)

$(FIG4_2_PDF): $(FIG4_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG4_2_PDF) $(FIG4_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG4_2_PDF))_compressed.pdf $(FIG4_2_PDF)

$(FIG5_1_PDF): $(FIG5_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG5_1_PDF) $(FIG5_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG5_1_PDF))_compressed.pdf $(FIG5_1_PDF)

$(FIG5_2_PDF): $(FIG5_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG5_2_PDF) $(FIG5_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG5_2_PDF))_compressed.pdf $(FIG5_2_PDF)

$(FIG5_3_PDF): $(FIG5_3_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG5_3_PDF) $(FIG5_3_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG5_3_PDF))_compressed.pdf $(FIG5_3_PDF)

$(FIG5_4_PDF): $(FIG5_4_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG5_4_PDF) $(FIG5_4_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG5_4_PDF))_compressed.pdf $(FIG5_4_PDF)

$(FIG6_1_PDF): $(FIG6_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG6_1_PDF) $(FIG6_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG6_1_PDF))_compressed.pdf $(FIG6_1_PDF)

$(FIG6_2_PDF): $(FIG6_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG6_2_PDF) $(FIG6_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG6_2_PDF))_compressed.pdf $(FIG6_2_PDF)

$(FIG6_3_PDF): $(FIG6_3_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG6_3_PDF) $(FIG6_3_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG6_3_PDF))_compressed.pdf $(FIG6_3_PDF)

$(FIG6_4_PDF): $(FIG6_4_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG6_4_PDF) $(FIG6_4_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG6_4_PDF))_compressed.pdf $(FIG6_4_PDF)

$(FIG7_1_PDF): $(FIG7_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG7_1_PDF) $(FIG7_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG7_1_PDF))_compressed.pdf $(FIG7_1_PDF)

$(FIG7_2_PDF): $(FIG7_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG7_2_PDF) $(FIG7_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG7_2_PDF))_compressed.pdf $(FIG7_2_PDF)

$(FIG7_3_PDF): $(FIG7_3_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG7_3_PDF) $(FIG7_3_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG7_3_PDF))_compressed.pdf $(FIG7_3_PDF)

$(FIG7_4_PDF): $(FIG7_4_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG7_4_PDF) $(FIG7_4_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG7_4_PDF))_compressed.pdf $(FIG7_4_PDF)

$(FIG7_5_PDF): $(FIG7_5_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG7_5_PDF) $(FIG7_5_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG7_5_PDF))_compressed.pdf $(FIG7_5_PDF)

$(FIG7_6_PDF): $(FIG7_6_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG7_6_PDF) $(FIG7_6_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG7_6_PDF))_compressed.pdf $(FIG7_6_PDF)

$(FIG7_7_PDF): $(FIG7_7_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG7_7_PDF) $(FIG7_7_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG7_7_PDF))_compressed.pdf $(FIG7_7_PDF)

$(FIG7_8_PDF): $(FIG7_8_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG7_8_PDF) $(FIG7_8_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG7_8_PDF))_compressed.pdf $(FIG7_8_PDF)

$(FIG7_9_PDF): $(FIG7_9_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG7_9_PDF) $(FIG7_9_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG7_9_PDF))_compressed.pdf $(FIG7_9_PDF)

$(FIG8_1_PDF): $(FIG8_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG8_1_PDF) $(FIG8_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG8_1_PDF))_compressed.pdf $(FIG8_1_PDF)

$(FIG8_2_PDF): $(FIG8_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG8_2_PDF) $(FIG8_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG8_2_PDF))_compressed.pdf $(FIG8_2_PDF)

$(FIG9_1_PDF): $(FIG9_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG9_1_PDF) $(FIG9_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG9_1_PDF))_compressed.pdf $(FIG9_1_PDF)

$(FIG9_2_PDF): $(FIG9_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG9_2_PDF) $(FIG9_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG9_2_PDF))_compressed.pdf $(FIG9_2_PDF)

$(FIG10_PDF): $(FIG10_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG10_PDF) $(FIG10_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG10_PDF))_compressed.pdf $(FIG10_PDF)

$(FIG11_1_PDF): $(FIG11_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG11_1_PDF) $(FIG11_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG11_1_PDF))_compressed.pdf $(FIG11_1_PDF)

$(FIG11_2_PDF): $(FIG11_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG11_2_PDF) $(FIG11_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG11_2_PDF))_compressed.pdf $(FIG11_2_PDF)

$(FIG11_3_PDF): $(FIG11_3_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG11_3_PDF) $(FIG11_3_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG11_3_PDF))_compressed.pdf $(FIG11_3_PDF)

$(FIG11_4_PDF): $(FIG11_4_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG11_4_PDF) $(FIG11_4_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG11_4_PDF))_compressed.pdf $(FIG11_4_PDF)

$(FIG12_1_PDF): $(FIG12_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG12_1_PDF) $(FIG12_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG12_1_PDF))_compressed.pdf $(FIG12_1_PDF)

$(FIG12_2_PDF): $(FIG12_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG12_2_PDF) $(FIG12_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG12_2_PDF))_compressed.pdf $(FIG12_2_PDF)

$(FIG13_1_PDF): $(FIG13_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG13_1_PDF) $(FIG13_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG13_1_PDF))_compressed.pdf $(FIG13_1_PDF)

$(FIG13_2_PDF): $(FIG13_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG13_2_PDF) $(FIG13_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG13_2_PDF))_compressed.pdf $(FIG13_2_PDF)

$(FIG14_1_PDF): $(FIG14_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG14_1_PDF) $(FIG14_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG14_1_PDF))_compressed.pdf $(FIG14_1_PDF)

$(FIG14_2_PDF): $(FIG14_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG14_2_PDF) $(FIG14_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG14_2_PDF))_compressed.pdf $(FIG14_2_PDF)

$(FIG14_3_PDF): $(FIG14_3_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG14_3_PDF) $(FIG14_3_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG14_3_PDF))_compressed.pdf $(FIG14_3_PDF)

$(FIG15_1_PDF): $(FIG15_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG15_1_PDF) $(FIG15_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG15_1_PDF))_compressed.pdf $(FIG15_1_PDF)

$(FIG15_2_PDF): $(FIG15_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG15_2_PDF) $(FIG15_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG15_2_PDF))_compressed.pdf $(FIG15_2_PDF)

$(FIG16_1_PDF): $(FIG16_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG16_1_PDF) $(FIG16_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG16_1_PDF))_compressed.pdf $(FIG16_1_PDF)

$(FIG16_2_PDF): $(FIG16_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG16_2_PDF) $(FIG16_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG16_2_PDF))_compressed.pdf $(FIG16_2_PDF)

$(FIG17_PDF): $(FIG17_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG17_PDF) $(FIG17_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG17_PDF))_compressed.pdf $(FIG17_PDF)

$(FIG18_1_PDF): $(FIG18_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG18_1_PDF) $(FIG18_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG18_1_PDF))_compressed.pdf $(FIG18_1_PDF)

$(FIG18_2_PDF): $(FIG18_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG18_2_PDF) $(FIG18_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG18_2_PDF))_compressed.pdf $(FIG18_2_PDF)

$(FIG18_3_PDF): $(FIG18_3_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG18_3_PDF) $(FIG18_3_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG18_3_PDF))_compressed.pdf $(FIG18_3_PDF)

$(FIG19_PDF): $(FIG19_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG19_PDF) $(FIG19_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG19_PDF))_compressed.pdf $(FIG19_PDF)

$(FIG20_1_PDF): $(FIG20_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG20_1_PDF) $(FIG20_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG20_1_PDF))_compressed.pdf $(FIG20_1_PDF)
	
$(FIG20_2_PDF): $(FIG20_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG20_2_PDF) $(FIG20_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG20_2_PDF))_compressed.pdf $(FIG20_2_PDF)

$(FIG21_1_PDF): $(FIG21_1_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG21_1_PDF) $(FIG21_1_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG21_1_PDF))_compressed.pdf $(FIG21_1_PDF)

$(FIG21_2_PDF): $(FIG21_2_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG21_2_PDF) $(FIG21_2_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG21_2_PDF))_compressed.pdf $(FIG21_2_PDF)

$(FIG21_3_PDF): $(FIG21_3_SVG)
	$(FIG_CONVERT) --export-filename=$(FIG21_3_PDF) $(FIG21_3_SVG)
	$(PDF_COMPRESS) -sOutputFile=$(basename $(FIG21_3_PDF))_compressed.pdf $(FIG21_3_PDF)


clean: clean-cache

clean : clean-cache
	@$(RM) $(SRC_SLIDES).pdf
	@$(RM) $(SRC_FULL).pdf
	@$(RM) *.sty

clean-cache :
	@$(RM) $(CACHE_DIR)
	@$(RM) indent.log